services:
    _defaults:
        autowire: false
        public: true

    sonata.product.admin:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~, '@AppBundle\Services\Helper\FileHelper']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }

    sonata.course.admin:
        class: AppBundle\Admin\CourseAdmin
        arguments: [~, AppBundle\Entity\Course, ~, '@AppBundle\Services\Helper\FileHelper']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Course }

    sonata.user.admin:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }