services:
    _defaults:
        autowire: false
        public: true

    sonata.product.admin:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~, '@AppBundle\Services\Helper\FileHelper', '@AppBundle\Repository\ProductRepository']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }

    sonata.course.admin:
        class: AppBundle\Admin\CourseAdmin
        arguments: [~, AppBundle\Entity\Course, ~, '@AppBundle\Services\Helper\FileHelper', '@AppBundle\Repository\CourseRepository']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Course }

    sonata.user.admin:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~, '@AppBundle\Services\Helper\FileHelper', '@AppBundle\Repository\UserRepository']
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    sonata.note.admin:
        class: AppBundle\Admin\NoteAdmin
        arguments: [~, AppBundle\Entity\Note, ~, '@AppBundle\Repository\NoteRepository']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Note }