app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional

api_login_check:
    path: /api/login_check

fos_user_security_login:
    path:      /admin/login
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:      /admin/login_check
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:      /admin/logout
    defaults:  { _controller: FOSUserBundle:Security:logout }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin