security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_TRAINER: ROLE_USER
        ROLE_ADMIN: ROLE_TRAINER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/api
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                check_path: /admin/login_check
                failure_path: /admin/login
                login_path: /admin/login
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_USER }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/media/photos, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
