imports:
    - { resource: repositories.yml }

services:
    _defaults:
        autowire: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Services\Validator\CourseValidator: ~
    AppBundle\Services\Validator\CourseFiltersValidator: ~
    AppBundle\Services\Validator\UserValidator: ~