imports:
    - { resource: repositories.yml }
    - { resource: admins.yml }

services:
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Services\Validator\CourseValidator: ~
    AppBundle\Services\Validator\CourseFiltersValidator: ~
    AppBundle\Services\Validator\UserValidator: ~

    AppBundle\Services\Helper\FileHelper:
        arguments: ['%kernel.root_dir%']